* Replicação Minimal [%]
** Avaliar porque cada pode ter sido escolhido (em ordem que apareceu)
[[https://man7.org/linux/man-pages/man1/sar.1.html]]

Saída:

```
Appending 4_kbcached because the NMAE with it 0.052039131870232326 < 1.
Appending 0_cpu16_.soft because the NMAE with it 0.05195572468678865 < 0.052039131870232326.
Appending 1_X.dev.mapper.cloud..3.root_.ufsused because the NMAE with it 0.051830613911623136 < 0.05195572468678865.
Appending 5_cpu10_.irq because the NMAE with it 0.051768058524040386 < 0.051830613911623136.
Appending 2_cpu17_.soft because the NMAE with it 0.05173851847990409 < 0.051768058524040386.
Appending 1_i121_intr.s because the NMAE with it 0.051708978435767786 < 0.05173851847990409.
Appending 3_i709_intr.s because the NMAE with it 0.051655111296460415 < 0.051708978435767786.
Appending 4_cpu16_.irq because the NMAE with it 0.051648160697840104 < 0.051655111296460415.
Appending 0_cpu9_.sys because the NMAE with it 0.05162383360266903 < 0.051648160697840104.
Appending 3_dev252.1_svctm because the NMAE with it 0.05152826287163983 < 0.05162383360266903.
Appending 0_i253_intr.s because the NMAE with it 0.05150914872543398 < 0.05152826287163983.
Tempo para construir minimal dataset 5805.100864887238
11
Index(['4_kbcached', '0_cpu16_.soft', '1_X.dev.mapper.cloud..3.root_.ufsused',
       '5_cpu10_.irq', '2_cpu17_.soft', '1_i121_intr.s', '3_i709_intr.s',
       '4_cpu16_.irq', '0_cpu9_.sys', '3_dev252.1_svctm', '0_i253_intr.s'],
      dtype='object')
MINIMAL NMAE REG_TREE 0.05177153382335054
 TRAINING TIME MINIMAL REG_TREE 0.03694438934326172
MINIMAL NMAE RANDOM_FOREST 0.06050093543473099
 TRAINING TIME MINIMAL RANDOM FOREST 0.5445246696472168
```
*** DONE 4_kbcached
De uma máquina Webserver e transcoder

sobre memória cacheada usada pelo kernel.

Uma máquina que é responsável por reencodar e mudar o formato de arquivo de forma adequada, ou um webserver que pode ter algoritmos assim como o [[~/wiki/ic/MPEG-DASH.org]], dessa forma a decisão pode acarretar na perda de frame rate
*** DONE 0_cpu16_.soft
Sobre uso de cpu por processamento de rede via software.

De uma máquina network file storage

Obviamente observa que maior o load, maior demanda de uso de CPU para a máquina de storage remoto e menor pode ser o framerate (por QoS)
*** DEFERRED 1_X.dev.mapper.cloud..3.root_.ufsused
CLOSED: [2023-09-29 Fri 17:50]
De uma máquina network file storage
*** DONE 5_cpu10_.irq
Do load balancer
Tempo gasto pela CPU em processamento de interrupções

Como o load balancer atua como um dispositivo "porteiro" do sistema, ele é extremamente requisitado e sua demanda é diretamente ligada à demanda geral do sistema por clientes externos

Ao receber dados de uma interface, a placa de rede emite uma interrupção, logo uma maior quantidade de interrupções decorre de uma grande quantidade de tráfego de rede no load balancer, isso impacta o sistema como um todo de forma a reduzir o frame rate
*** DONE 0_cpu17_.soft
Igual à [[0_cpu16_.soft]]
*** DEFERRED 1_i121_intr.s
CLOSED: [2023-09-29 Fri 17:49]
De uma máquina NFS
*** DEFERRED 3_i709_intr.s
CLOSED: [2023-09-29 Fri 17:50]
De uma máquina Webserver e transcoder
*** DONE 4_cpu16_.irq
Assim como o [[* 5_cpu10_.irq]], porém nesse caso numa máquina de webserver/transcoding.

Mais interrupções quando tem mais processamento de rede pela placa de rede, então pode estar ligado ao gargalo que faz cair.

*** OBSERVE QUE TODOS ESSES ANTERIORES SÃO DO CLUSTER.C
